### ISSUE TITLE
Not use GPU failed call to cuInit: CUDA_ERROR_NO_DEVICE

### ISSUE THREAD

**Issue by letusfly85** [rail-berkeley/softlearning#150]
I got the following error when I run it on a Nvidia Machine (V100) .

What is wrong..? 🤔 

### Errors

```bash
(pid=152519) 2020-09-14 16:54:07.435098: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
(pid=152519) 2020-09-14 16:54:07.442265: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
```

```bash
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

### case. 1

```bash
softlearning run_example_local examples.development \
    --algorithm SAC \
    --universe dm_control \
    --domain walker \
    --task walk \
    --exp-name sl-sac \
    --checkpoint-frequency 1000
```

### case. 2

Adding `CUDA_VISIBLE_DEVICES` is meeningless.. same error happened.

```bash
export CUDA_VISIBLE_DEVICES="0"

softlearning run_example_local examples.development \
    --algorithm SAC \
    --universe dm_control \
    --domain walker \
    --task walk \
    --exp-name sl-sac \
    --checkpoint-frequency 1000
```

## Tensorflow versions

Here is my environment. I used conda.

```
pip freeze | grep tensor
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensorboardX==2.1
tensorflow==2.3.0
tensorflow-addons==0.11.2
tensorflow-estimator==2.3.0
tensorflow-gpu==2.3.0
tensorflow-probability==0.11.0
```

**Comment by hartikainen** [comment]
Does it work if you add `--trial-gpus=1.0` to your cli arguments?

**Comment by letusfly85** [comment]
@hartikainen 

Thank you.
I finally modified like below, and it works fine!

```bash
# set CUDA_VISIBLE_DEVICES
export CUDA_VISIBLE_DEVICES="0"

# downgrade tensorflow libraries
pip install tensorflow==2.2.0 tensorflow-gpu==2.2.0 tensorflow-probability==0.10.0

# add `--trial-gpus=1.0` option
softlearning run_example_local examples.development \
     --trial-gpus=1.0  \
    --algorithm SAC \
    --universe dm_control \
    --domain walker \
    --task walk \
    --exp-name sl-sac \
    --checkpoint-frequency 1000
```

but, I use only 500MB around, is it right...? 🤔 

```bash
nvidia-smi


| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     75810      C   ray::ExperimentRunner.train()                507MiB |
+-----------------------------------------------------------------------------+
```

**Comment by hartikainen** [comment]
That looks good! The standard experiments don't use much gpu memory and it's actually unlikely that you'll find much speedups when running a single trial. The gpu will become much more useful when running experiments from vision (i.e. with much larger inputs to the networks) or if you run many trials in parallel.

**Comment by letusfly85** [comment]
Thank you!
